/* export_c_tables.c -- 把 build_tables() 的結果輸出成 C 初始化列表 (ref_tables.inc)
 *   gcc -O2 -o export_c_tables export_c_tables.c && ./export_c_tables > ref_tables.inc
 */
#define main solver_main          /* 借用 solver_opt.c 的函式，避開它的 main */
#include "solver_opt.c"
#undef main

static void dump_u16_rows(const char *decl, const uint16_t *v, unsigned rows,
                          unsigned cols)
{
    printf("%s = {\n", decl);
    for (unsigned r = 0; r < rows; ++r) {
        printf("  {\n");
        for (unsigned i = 0; i < cols; ++i)
            printf("%s%u%s", i % 16 == 0 ? "    " : " ", v[r * cols + i],
                   i + 1 == cols ? "\n" : (i % 16 == 15 ? ",\n" : ","));
        printf("  }%s\n", r + 1 == rows ? "" : ",");
    }
    puts("};");
}

static void dump_u8(const char *decl, const uint8_t *v, unsigned n)
{
    printf("%s = {\n", decl);
    for (unsigned i = 0; i < n; ++i)
        printf("%s%u%s", i % 32 == 0 ? "    " : " ", v[i],
               i + 1 == n ? "\n" : (i % 32 == 31 ? ",\n" : ","));
    puts("};");
}

int main(void)
{
    if (!build_tables())
        return 1;
    puts("/* generated by export_c_tables.c -- do not edit */");
    dump_u16_rows("static uint16_t permutation[3][PERMUTATIONS]",
                  &permutation[0][0], 3, PERMUTATIONS);
    dump_u16_rows("static uint16_t orientation[3][ORIENTATIONS]",
                  &orientation[0][0], 3, ORIENTATIONS);
    dump_u8("static uint8_t permutation_distance[PERMUTATIONS]",
            permutation_distance, PERMUTATIONS);
    dump_u8("static uint8_t orientation_distance[ORIENTATIONS]",
            orientation_distance, ORIENTATIONS);
    return 0;
}
